### ISSUE TITLE
Export Spectrum into CSV

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/specio#20]
We need to be able to export a `specio.core.Spectrum` into CSV.

**Comment by glemaitre** [comment]
@jorisvandenbossche I would need your pandas skill. Do you have any suggestion on how to store into a dataframe. Also what do you think about the metadata. It could be nice to keep them, isn't it?

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/paris-saclay-cds/specio/pull/45
